### Python ID3实现

使用第三方库[decision-tree-id3](https://pypi.org/project/decision-tree-id3/).不过这里也同时实现了剪枝(`pruning`)和信息增益比(`Information gain ratio`)...不过这两个参数都是optional的，所以设置为`False`也就成了一般的ID3了。
>到这里感觉没有必要纠结各种不同算法的实现了，实际使用的时候直接用比较好算法就是了...比如剪枝的CART和C4.5等。

In [27]:
from sklearn.datasets import load_iris
from id3 import Id3Estimator
from id3 import export_graphviz, export_text

In [28]:
iris = load_iris()
estimator = Id3Estimator()
estimator.fit(iris.data, iris.target)

Id3Estimator(gain_ratio=False, is_repeating=False, max_depth=None,
       min_entropy_decrease=0.0, min_samples_split=2, prune=False)

In [29]:
# 预测
estimator.predict(iris.data[0])

/home/shensir/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [31]:
print(iris.data[0].reshape(1, -1))
estimator.predict(iris.data[0].reshape(1, -1))

[[ 5.1  3.5  1.4  0.2]]


array([0])

In [32]:
print(export_text(estimator.tree_, iris.feature_names))


petal length (cm) <=2.45: 0 (50) 
petal length (cm) >2.45
|   petal width (cm) <=1.75
|   |   sepal length (cm) <=7.10
|   |   |   sepal width (cm) <=2.85: 1 (27/4) 
|   |   |   sepal width (cm) >2.85: 1 (22) 
|   |   sepal length (cm) >7.10: 2 (1) 
|   petal width (cm) >1.75
|   |   sepal length (cm) <=5.95
|   |   |   sepal width (cm) <=3.10: 2 (6) 
|   |   |   sepal width (cm) >3.10: 1 (1) 
|   |   sepal length (cm) >5.95: 2 (39) 



In [33]:
# 同样也可以转化为图片形式
export_graphviz(estimator.tree_, 'tree.dot', bunch.feature_names)
# 之后终端运行dot -Tpdf tree.dot -o tree.pdf

<_io.TextIOWrapper name='tree.dot' mode='w' encoding='utf8'>